version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: toyota-backend:v1
    container_name: toyota-backend
    env_file:
      - ./backend/configs/.env
    ports:
      - "3003:3003"
    networks:
      - toyota-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: toyota-frontend:v1
    container_name: toyota-frontend
    ports:
      - "3051:80"
    depends_on:
      - backend
    networks:
      - toyota-network
    restart: unless-stopped

networks:
  toyota-network:
    driver: bridge
